language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

matrix:
    exclude:
        - php: hhvm
mysql:
    database: moodle
    username: root
    encoding: utf8

before_install:
    - curl -sS https://getcomposer.org/installer | php
    - sudo apt-get update > /dev/null
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    - mkdir moodledata
    - git clone https://github.com/moodle/moodle.git moodle
    - mysql -e 'create database moodle;'
    - sudo chown www-data moodle
    - export DBNAME=moodle
    - export DBUSER=root
    - export DBPASSWORD=
    - export MOODLEDATA=moodledata
    - export MOODLEDIR=moodle
    - cd moodle/admin/cli
    - sudo -u www-data php install.php ---wwwroot=moodle --dataroot=moodledata --fullname=test --shortname=test -adminuser=test --adminpass=Test1234! --non-interactive
    - cd ../..
    - sudo chown -R root moodle

install:
    - ./composer.phar install

script: php ./tests/scripts/run-tests.php
