language: php

php:
  - 5.5

mysql:
  database: moodle
  username: root
  encoding: utf8

env:
  - DB=mysqli

before_install:
  - curl -sS https://getcomposer.org/installer | php
  - sudo apt-get update > /dev/null
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo service apache2 restart
  - ps aux | grep apache2
  - asdshafg
  - git clone https://github.com/moodle/moodle.git moodle
  - cd moodle
  - cp config-dist.php config.php
  - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*phpu\)%\n\1%' config.php"
  - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
  - sh -c "if [ '$DB' = 'mysqli' ]; then sed -i -e s/\'pgsql\'/\'mysqli\'/ -e s/\'username\'/\'root\'/ config.php; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database moodle;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'username\'/\'postgres\'/ config.php; fi"
  - mkdir -m777 $HOME/moodledata
    #- php admin/tool/phpunit/cli/init.php
  - cd ..

script: bash tests/commands/user-create.sh
